# PDF2Anki Configuration Template
# Copy this file to settings.yaml and fill in your API keys

# API Keys (REQUIRED: set your actual keys here)
api_keys:
  openai: "sk-your-openai-api-key-here"
  anthropic: "sk-ant-your-anthropic-api-key-here"  # Optional

# OCR Settings
ocr:
  engine: "paddle"  # "paddle" or "pix2text"
  paddle:
    use_gpu: false  # Set to true if you have CUDA GPU
    lang: "ja+en"   # Adjust based on your PDF language
  formula:
    enabled: true
    model: "PP-FormulaNet-L"  # Use "PP-FormulaNet-S" for faster processing

# LLM Settings  
llm:
  primary_model: "gpt-4o"  # "gpt-4o" or "claude-3.5-sonnet"
  openai:
    temperature: 0.1  # Keep low for consistent LaTeX output
  self_refine:
    enabled: true
    max_attempts: 3

# PDF Processing
pdf:
  dpi: 300  # Higher DPI = better quality but slower processing

# Card Generation
card_generation:
  extract_types:
    - "定義"
    - "定理" 
    - "命題"
    - "補題"
  dependency_analysis:
    enabled: true

# Output Settings
output:
  structure: "by_chapter"
  obsidian:
    vault_path: "/path/to/your/obsidian/vault"  # Optional: set your vault path
    
# Logging
logging:
  level: "INFO"  # Use "DEBUG" for troubleshooting